rails:
  build: .
  hostname: rails-staging
  container_name: rails-staging
  environment:
    - VIRTUAL_HOST=shirasagi.docker # for dinghy
    - HTTPS_METHOD=noredirect # for dinghy
    - SERVER_ENV=development
    - RAILS_ENV=development
    - DATABASE_HOST=mongo-staging
  volumes:
    - "/data/shirasagi/public:/var/www/shirasagi/public"
  ports:
    - "8080:3000"
  links:
    - mongo
  log_opt:
      max-size: 32m
      max-file: "5"

mongo:
  image: mongo:3.3.12
  hostname: mongo-staging
  container_name: mongo-staging
  ports:
    - "27018:27017"
  volumes:
    - "/data/shirasagi-staging/mongo:/data/db"
  environment:
    VIRTUAL_HOST: mongo.shirasagi.docker # for dinghy
    HTTPS_METHOD: noredirect # for dinghy
  log_opt:
      max-size: 32m
      max-file: "5"
